# Generated by Django 5.0.1 on 2024-02-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_profile_info_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
