# Generated by Django 5.0.1 on 2024-03-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='canceled',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
