# Generated by Django 5.0.1 on 2024-03-10 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_appointment_canceled_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='provider_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='patient_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
