# Generated by Django 5.0.1 on 2024-03-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='facility_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
