# Generated by Django 5.0.1 on 2024-04-10 13:59

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
